language: php

sudo: false

env:
  - LARAVEL_VERSION=5.8.*
  
matrix:
  include:
    - php: 7.2
      env: LARAVEL_VERSION=5.8.*
    - php: 7.2
      env: LARAVEL_VERSION=6.0.*

before_install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update

before_script:
  - composer install --prefer-source --no-interaction

cache:
  directories:
    - $HOME/.composer/cache